#
# ZenMagick admin URL mappings
#
#

## global mappings
global:
  success:
    view: redirect
  error:
    template: error
    layout: 
  success-demo:
    view: redirect#requestId=index
  store-view:
    view: storeView

## page mappings    
page:
  login:
    success:
      view: redirect#requestId=index
    logged-in:
      view: redirect#requestId=index
  logoff:
    success:
      view: redirect#requestId=login
  reset_password:
    success:
      view: redirect#requestId=login
  update_user:
    formId: updateUser
    form: ZMAdminUserForm
    success:
      view: redirect#requestId=index
  edit_admin_user:
    formId: adminUser
    form: ZMAdminUserForm
    success:
      view: redirect#requestId=admin_users
  cache_admin:
    success:
      view: redirect#requestId=cache_admin
  plugins:
    success-install:
      view: redirect#requestId=plugins
    success-uninstall:
      view: redirect#requestId=plugins
    success-upgrade:
      view: redirect#requestId=plugins
    success-enable:
      view: redirect#requestId=plugins
    success-disable:
      view: redirect#requestId=plugins
    plugin-conf:
      layout: 
      template: plugin_conf
  legacy-config:
    success:
      view: redirect#requestId=legacy-config
