#
# ZenMagick admin URL mappings
#
#

## global mappings
global:
  success:
    view: redirect
  error:
    template: views/error.php
    layout:
  success-demo:
    view: redirect#requestId=index

## page mappings
page:
  login:
    success:
      view: redirect#requestId=index
    logged-in:
      view: redirect#requestId=index
  logoff:
    success:
      view: redirect#requestId=login
  reset_password:
    success:
      view: redirect#requestId=login
  update_user:
    formId: updateUser
    form: ZenMagick\apps\admin\Forms\AdminUserForm
    success:
      view: redirect#requestId=index
  edit_admin_user:
    formId: adminUser
    form: ZenMagick\apps\admin\Forms\AdminUserForm
    success:
      view: redirect#requestId=admin_users
  cache_admin:
    success:
      view: redirect#requestId=cache_admin
  plugins:
    success-install:
      view: redirect#requestId=plugins
    success-uninstall:
      view: redirect#requestId=plugins
    success-upgrade:
      view: redirect#requestId=plugins
    success-enable:
      view: redirect#requestId=plugins
    success-disable:
      view: redirect#requestId=plugins
    plugin-conf:
      layout:
      template: views/plugin_conf.php
  legacy-config:
    success:
      view: redirect#requestId=legacy-config
  ezpage:
      controller: ZenMagick\apps\admin\Controller\EzpagesController
      template: views/ezpages-details.php
  ezpages:
      controller: ZenMagick\apps\admin\Controller\EzpagesController
      template: views/ezpages-overview.php
  zc_admin:
    controller: ZenMagick\ZenCartBundle\Controller\AdminController
