parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     zenmagick
    database_user:     root
    database_password: ~
    table_prefix:      ""

    mailer_transport:  mail
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~
    mailer_port:       ~
    mailer_encryption: ~
    mailer_disable_delivery: false
    mailer_delivery_address: ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    session_timeout: 1440
    session_handler: session.handler.pdo
    session.class: "ZenMagick\Http\Session\Session"

    zenmagick.plugins.enabled: false
