##
## Shared ZenMagick email config
##

services:
  zencartTransport:
    class: apps\store\bundles\ZenCartBundle\utils\ZenCartTransport
    scope: container

swiftmailer:
## using the legacy transport
#  transport: zencartTransport
  transport: %zenmagick.core.email.transport%
  username: %zenmagick.core.email.smtp.user%
  password: %zenmagick.core.email.smtp.password%
  host: %zenmagick.core.email.smtp.host%
  port: %zenmagick.core.email.smtp.port%
#  spool:
#    type: file
#    path: %zenmagick.cacheBaseDir%/swiftmailer/spool
  sender_address: %storeEmail%
  antiflood:
    threshold: 99
    sleep: 0
  logging: true
