#
# default settings
#

zenmagick:
  bundles: {}

  base:
    events:
      listeners:
        - zenmagick\base\EventListener
        - zenmagick\http\EventListener
        - zenmagick\apps\sample\EventHandler

  mvc:
    view:
      defaultLayout: default_layout.php
