#
# default settings
#

zenmagick:
  base:
    events:
      listeners:
        - zenmagick\apps\sample\EventHandler
        - zenmagick\apps\sample\EventListener #rename EventHandler to this!
        - zenmagick\base\EventListener
        - zenmagick\http\EventListener
