zenmagick:
  version: '0.9.13.2'
  core:
    fs:
      permissions:
        fix: true
        defaults:
          file: 0666
          folder: 0777

  mvc:
    ## rpc
    rpc:
      format: JSON


  http:
    ## html
    html:
      charset: utf-8
    view:
      defaultLayout: default_layout.html.twig
    ## templates
    templates:
      ext: .html.twig

storeDefaultLanguageId: 1

#  price calculation decimals for rounding
calculationDecimals: 4

# HTML generation / validation
isAutoJSValidation: true


