imports:
    ## defaults
    - { resource: container.yaml }
    ## shared defaults
    - { resource: ../../../config/store-container.yaml }
    ## custom
    - { resource: ../../../config/store/container-production.yaml, mode: append }
